# Generated by Django 4.1.1 on 2022-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blog_body_alter_portfolio_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
