# Generated by Django 4.1.1 on 2022-09-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_portfolio_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('range', 'Orange'), ('blue_violet', 'Blue Violet'), ('violet', 'Violet'), ('yello_green', 'Yello Green'), ('lime_green', 'Lime Green'), ('gold', 'Gold'), ('aqua', 'Aqua')], default=None, max_length=20)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
